# Generated by Django 4.2.1 on 2024-05-13 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='auctions.category'),
        ),
    ]
