# Generated by Django 4.2.1 on 2024-05-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_products_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='initialprice',
        ),
        migrations.AddField(
            model_name='products',
            name='nitialprice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
