# Generated by Django 4.2.1 on 2024-05-15 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_products_initialprice_products_nitialprice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='nitialprice',
            new_name='initialprice',
        ),
    ]
